#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$project_root"

command -v docker >/dev/null 2>&1 || { echo "Docker is required. Install Docker Engine first." >&2; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "Docker Compose v2 is required." >&2; exit 1; }

generated_password=""
if [[ ! -f .env ]]; then
    command -v openssl >/dev/null 2>&1 || { echo "openssl is required to generate the bootstrap password." >&2; exit 1; }
    generated_password="$(openssl rand -base64 24 | tr -d '\n' | tr '/+' 'ab' | cut -c1-32)"
    umask 077
    {
        printf '%s\n' '# Generated by scripts/quick_start.sh'
        printf 'SERVER_MONITOR_INITIAL_PASSWORD=%s\n' "$generated_password"
        printf '%s\n' 'SERVER_MONITOR_PORT=8000'
    } > .env
    echo "Created .env with a random bootstrap password."
fi

docker compose up -d --build
container_id="$(docker compose ps -q server-monitor)"
if [[ -z "$container_id" ]]; then
    echo "The container did not start." >&2
    docker compose logs --tail=100 server-monitor >&2 || true
    exit 1
fi

for _ in {1..45}; do
    status="$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$container_id" 2>/dev/null || true)"
    case "$status" in
        healthy)
            port="$(sed -n 's/^SERVER_MONITOR_PORT=//p' .env | tail -n 1)"
            [[ "$port" =~ ^[0-9]+$ ]] || port=8000
            echo "Server Monitor is ready: http://127.0.0.1:${port}"
            if [[ -n "$generated_password" ]]; then
                echo "Bootstrap login: admin / ${generated_password}"
                echo "Change this password on first login, then remove SERVER_MONITOR_INITIAL_PASSWORD from .env."
            fi
            exit 0
            ;;
        unhealthy|exited|dead)
            echo "The container became unhealthy (status: $status)." >&2
            docker compose logs --tail=100 server-monitor >&2 || true
            exit 1
            ;;
    esac
    sleep 2
done

echo "Timed out waiting for the health check." >&2
docker compose logs --tail=100 server-monitor >&2 || true
exit 1
